// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTfkqtlRmxahHym8n43Mn6kMPWnqR6Q_Y',
    appId: '1:622653277827:web:754ff8869e2116c9b47db6',
    messagingSenderId: '622653277827',
    projectId: 'attendanceapp-d36a1',
    authDomain: 'attendanceapp-d36a1.firebaseapp.com',
    databaseURL: 'https://attendanceapp-d36a1-default-rtdb.firebaseio.com',
    storageBucket: 'attendanceapp-d36a1.appspot.com',
    measurementId: 'G-F27W2QWSG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGV_HpSFuXZzLswMUpLeD2rwk4Isef2Q',
    appId: '1:622653277827:android:1c1fb893076be43cb47db6',
    messagingSenderId: '622653277827',
    projectId: 'attendanceapp-d36a1',
    databaseURL: 'https://attendanceapp-d36a1-default-rtdb.firebaseio.com',
    storageBucket: 'attendanceapp-d36a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyZ4T1ihE0PZecGKNopwTLSQAOdlmCfa4',
    appId: '1:622653277827:ios:fa11f4b6a56649feb47db6',
    messagingSenderId: '622653277827',
    projectId: 'attendanceapp-d36a1',
    databaseURL: 'https://attendanceapp-d36a1-default-rtdb.firebaseio.com',
    storageBucket: 'attendanceapp-d36a1.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyZ4T1ihE0PZecGKNopwTLSQAOdlmCfa4',
    appId: '1:622653277827:ios:fa11f4b6a56649feb47db6',
    messagingSenderId: '622653277827',
    projectId: 'attendanceapp-d36a1',
    databaseURL: 'https://attendanceapp-d36a1-default-rtdb.firebaseio.com',
    storageBucket: 'attendanceapp-d36a1.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTfkqtlRmxahHym8n43Mn6kMPWnqR6Q_Y',
    appId: '1:622653277827:web:5c7669d506a3eac1b47db6',
    messagingSenderId: '622653277827',
    projectId: 'attendanceapp-d36a1',
    authDomain: 'attendanceapp-d36a1.firebaseapp.com',
    databaseURL: 'https://attendanceapp-d36a1-default-rtdb.firebaseio.com',
    storageBucket: 'attendanceapp-d36a1.appspot.com',
    measurementId: 'G-9Y25NGSYZD',
  );
}
